language: python
node_js:
      - "0.10"
before_install: npm install -g grunt-cli
install: 
    - pip install -r requirements.txt
    - npm install
    - bower install
before_script: grunt
script: echo "test"
